services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql+psycopg2://postgres:567234@repository:5432/hw02
    depends_on:
      - db
    ports:
      - "8000:8000"  # app will be available at http://localhost:8000

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    ports:
      - "5432:5432"  # PostgreSQL will be available at http://localhost:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
